/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.BarberShop;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //Connection test
        com.database.DBConnection.getConnection();
    }
}
